name: github_trend
description: github trending api for dart
version:  0.1.0
homepage: https://github.com/huangyanxiong01/github_trending
author: Freax <https://www.myfreax.com/>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  html: ^0.14.0+1


dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
