name: github_trend
description: Get the popular repository on github,You can also get all the languages.And convert the data into Map, List, JSON
version:  1.1.8
homepage: https://github.com/huangyanxiong01/github_trending
author: Freax <https://www.myfreax.com/>
environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  html: ^0.14.0+1


dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
